[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=node_modules/forge-std/src/"
]
